# author: Ondrej Deingruber
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [-0.08, -0.10], [0.21, -0.10], [0.21, 0.10], [-0.08, 0.10] ] 
inflation_radius: 0.2
cost_scaling_factor: 15

transform_tolerance: 1.5

publish_voxel_map : True


