# author: Ondrej Deingruber
fit_bot:
  hardware_interface:
    joints:
      - imaginary_center_front_wheel_steering_joint
      - imaginary_center_back_wheel_joint 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: position_controllers/JointPositionController
    joint: imaginary_center_front_wheel_steering_joint
    pid: {p: 1.0, i: 100.0, d: 0.5}

  joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: imaginary_center_back_wheel_joint

  mobile_base_controller:
    type        : "ackermann_steering_controller/AckermannSteeringController"
    rear_wheel: 'imaginary_center_back_wheel_joint'
    front_steer: 'imaginary_center_front_wheel_steering_joint'
    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.05, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.05, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation between the rear and the front, and diameter of the rear. 
    # These are both optional.
    # ackermann_steering_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter.
    wheel_separation_h : 0.16
    wheel_radius : 0.04

    # Wheel separation and radius multipliers for odometry calibration.
    wheel_separation_h_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Steer position angle multipliers for fine tuning.
    steer_pos_multiplier       : 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5


    # Base frame_id
    base_frame_id: base_footprint

    # Odom frame_id
    odom_frame_id: odom

    enable_odom_tf: false

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.25  # m/s
        min_velocity           : -0.25 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.2  # m/s^2 - tune
        min_acceleration       : -0.2 # m/s^2 - tune
        has_jerk_limits        : true
        max_jerk               : 5.0 # m/s^3 - tune

    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.1  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2 - tune
        has_jerk_limits        : true
        max_jerk               : 2.5 # rad/s^3 - tune