# author: Ondrej Deingruber
local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.08

  obstacle_2d_layer:
    observation_sources: laser_scan_sensor
    observation_persistence: 2.0

    laser_scan_sensor: {sensor_frame: base_footprint, data_type: LaserScan, topic: /fit_bot/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 0.5}
  
  plugins:
  - {name: obstacle_2d_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
  # - {name: static_layer, type: "costmap_2d::StaticLayer"}