# author: Ondrej Deingruber
TebLocalPlannerROS:
  # robot configuration parameters
  acc_lim_x: 0.2
  acc_lim_theta: 0.2
  max_vel_x: 0.2
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.4 # theoretically 0.82644
  min_turning_radius: 0.26 # theoretically 0.2393
  wheelbase: 0.16
  cmd_angle_instead_rotvel: true
  footprint_model:
    type: "polygon"
    vertices: [ [-0.08, -0.10], [0.21, -0.10], [0.21, 0.10], [-0.08, 0.10] ]

  # goal tolerance parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  free_goal_vel: false

  # trajectory configuration parameters
  dt_ref: 0.5
  dt_hysteresis: 0.1
  min_samples: 3
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -0.1
  max_global_plan_lookahead_dist: 3.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 4
  publish_feedback: false
  shrink_horizon_backup: true
  allow_init_with_backwards_motion: true
  exact_arc_length: false
  shrink_horizon_min_duration: 10.0

  # obstacle parameters
  min_obstacle_dist: 0.08
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.25
  obstacle_poses_affected: 20
  inflation_dist: 0.10
  include_dynamic_obstacles: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5

  # optimalization parameters
  no_inner_iterations: 3
  no_outer_iterations: 2

  # parallel planning
  enable_homotopy_class_planning: false

  odom_topic: "odom"
  map_frame: "map"